"""End-to-end Producer-Consumer runner for EduClaw/Manim keyframe streaming."""

from __future__ import annotations

import json
import os
import queue
import sys
import threading
import time
from pathlib import Path
from typing import Any, Callable

from apps.educlaw.streaming_engine.consumer import (
    assemble_slide_chunks,
    render_single_slide,
)
from apps.educlaw.streaming_engine.models import SlideData
from apps.educlaw.streaming_engine.producer import generate_lecture_stream


def run_producer_consumer(
    prompt: str,
    *,
    output_dir: str | Path | None = None,
    base_url: str | None = None,
    api_key: str | None = None,
    model: str | None = None,
    total_slides: int = 3,
    quality: str = "low_quality",
    on_progress: Callable[[str, str], None] | None = None,
) -> dict[str, Any]:
    """Execute the full Producer-Consumer pipeline in one go.

    - Spawns the Producer thread to generate pedagogical slides with voice narration.
    - Consumer thread renders each slide into a discrete MP4 chunk with synced voice narration.
    - Assembles all chunks into a final cohesive MP4 video.
    - Writes manifest.json and returns a complete result dictionary.
    """
    if output_dir:
        run_dir = Path(output_dir).resolve()
    else:
        run_id = f"run_{int(time.time() * 1000)}"
        curr = Path(__file__).resolve()
        repo_root = None
        for parent in [curr, *curr.parents]:
            if (parent / "pyproject.toml").is_file() and (parent / "apps").is_dir():
                repo_root = parent
                break
        root = repo_root or Path.cwd()
        run_dir = (root / "apps" / "agents" / "workspace" / "producer_consumer_runs" / run_id).resolve()

    run_dir.mkdir(parents=True, exist_ok=True)

    def _notify(stage: str, msg: str = ""):
        if on_progress:
            try:
                on_progress(stage, msg)
            except Exception:
                pass
        print(f"-> {stage} {msg}".strip(), file=sys.stderr, flush=True)

    slide_queue: queue.Queue = queue.Queue()

    # 1. Start Producer Thread
    producer_thread = threading.Thread(
        target=generate_lecture_stream,
        args=(prompt, slide_queue),
        kwargs={
            "base_url": base_url,
            "api_key": api_key,
            "model": model,
            "total_slides": total_slides,
            "on_progress": on_progress,
        },
        daemon=True,
    )
    producer_thread.start()

    # 2. Consumer Execution Loop
    rendered_chunks: list[Path] = []
    slide_records: list[dict[str, Any]] = []
    combined_code_parts: list[str] = [
        "# Auto-generated by AOS Producer-Consumer Keyframe Generator",
        "from manim import *",
        "from manim_voiceover import VoiceoverScene",
        "from tools.aos_speech_service import AOSSpeechService\n",
    ]

    while True:
        try:
            slide_data: SlideData = slide_queue.get(timeout=1.0)
        except queue.Empty:
            if not producer_thread.is_alive():
                break
            continue

        _notify("VALIDATING_CODE", f"Validating code for Slide {slide_data.slide_num}")
        _notify("RENDERING", f"Rendering Slide {slide_data.slide_num} with voice narration")

        # Render slide MP4 chunk
        chunk_path: Path | None = None
        try:
            chunk_web_or_abs = render_single_slide(slide_data, output_dir=run_dir, quality=quality)
            p = Path(chunk_web_or_abs)
            if p.is_file():
                chunk_path = p
            else:
                for cand in run_dir.glob(f"*slide_{slide_data.slide_num}*.mp4"):
                    if cand.is_file():
                        chunk_path = cand
                        break
            if chunk_path and chunk_path.is_file():
                rendered_chunks.append(chunk_path)
        except Exception as exc:
            print(f"[Consumer Warning] Slide {slide_data.slide_num} render failed: {exc}", file=sys.stderr)

        combined_code_parts.append(
            f"# --- Slide {slide_data.slide_num} ---\n"
            f"# Narration: {slide_data.narration}\n"
            f"{slide_data.python_code}\n"
        )
        slide_records.append({
            "slide_num": slide_data.slide_num,
            "narration": slide_data.narration,
            "code": slide_data.python_code,
            "chunk_path": str(chunk_path) if chunk_path and chunk_path.is_file() else None,
        })

        if slide_data.is_final:
            break

    producer_thread.join(timeout=30)

    # 3. Assemble final video from chunks
    final_video = run_dir / "final.mp4"
    if rendered_chunks:
        _notify("assemble", "Assembling final video with synchronized narration")
        assemble_slide_chunks(rendered_chunks, final_video)
        _notify("VALIDATING_VIDEO", "Validating output animation video")

    # Save combined code file
    scene_file = run_dir / "scene.py"
    scene_file.write_text("\n".join(combined_code_parts), encoding="utf-8")

    manifest = {
        "ok": final_video.is_file() and final_video.stat().st_size > 0,
        "mode": "animate",
        "prompt": prompt,
        "run_dir": str(run_dir),
        "video_path": str(final_video) if final_video.is_file() else None,
        "scene_file": str(scene_file),
        "total_slides": len(slide_records),
        "slides": slide_records,
        "has_audio": True,
    }
    manifest_path = run_dir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    _notify("upload", "Animation and narration ready")

    return manifest
