"""Animate workflow module for Manim animations with voiceover narration."""

from .contracts import (
    AnimationCall,
    Audience,
    CompileError,
    CompileResult,
    FailureCategory,
    FinalCode,
    KnowledgeResult,
    LessonPlan,
    NarrationPlan,
    NarrationStep,
    OutputType,
    PipelineState,
    RagChunk,
    RequestClassification,
    SceneObject,
    SceneStep,
    VideoPlan,
    VisualStyle,
    VoiceoverBookMark,
)
from .loop import WorkflowOrchestrator, build_agents, normalize_lesson_plan

__all__ = [
    "AnimationCall",
    "Audience",
    "CompileError",
    "CompileResult",
    "FailureCategory",
    "FinalCode",
    "KnowledgeResult",
    "LessonPlan",
    "NarrationPlan",
    "NarrationStep",
    "OutputType",
    "PipelineState",
    "RagChunk",
    "RequestClassification",
    "SceneObject",
    "SceneStep",
    "VideoPlan",
    "VisualStyle",
    "VoiceoverBookMark",
    "WorkflowOrchestrator",
    "build_agents",
    "normalize_lesson_plan",
]
