"""Ontology package exports."""

from aos_lkg.ontology.capabilities import (
    CAPABILITY_DEFINITIONS,
    CONCEPT_DEFINITIONS,
    ALGORITHM_DEFINITIONS,
)
from aos_lkg.ontology.manim_mappings import (
    MANIM_MAPPING_DEFINITIONS,
    ANIMATION_PATTERN_DEFINITIONS,
    PRECISION_RULE_DEFINITIONS,
    CODE_EXAMPLE_DEFINITIONS,
)
from aos_lkg.ontology.enrichment import (
    enrich_knowledge_graph,
    API_CAPABILITY_MAPPINGS,
    API_ALGORITHM_MAPPINGS,
    API_ALTERNATIVES,
)

__all__ = [
    "CAPABILITY_DEFINITIONS",
    "CONCEPT_DEFINITIONS",
    "ALGORITHM_DEFINITIONS",
    "MANIM_MAPPING_DEFINITIONS",
    "ANIMATION_PATTERN_DEFINITIONS",
    "PRECISION_RULE_DEFINITIONS",
    "CODE_EXAMPLE_DEFINITIONS",
    "enrich_knowledge_graph",
    "API_CAPABILITY_MAPPINGS",
    "API_ALGORITHM_MAPPINGS",
    "API_ALTERNATIVES",
]
